### PR TITLE
zip/zip gives error with rubyzip > 0.9

### PR DESCRIPTION
**Pull request by R-i-c-k-y**
Changing with zip-zip works for me.  (I use rubyzip v.1.1.0)

Thanks for your great work!

### CODE REVIEW

**Comment by two-pack** [comment]
Please show more detail of error and fixed information.
And did you check old rubyzip on your pacth?

**Comment by R-i-c-k-y** [comment]
I told you everything, showed patch (zip-zip instead of zip/zip, in
init.rb): all is working, now!
I didn't check old versions of rubyzip, having installed 1.0.0 and 1.1.0

Riccardo

**Comment by two-pack** [comment]
'zip/zip' is written on Important note of https://github.com/rubyzip/rubyzip.

**Comment by R-i-c-k-y** [comment]
Yes, I know.... in your plugin you require zip/zip but, as you read in
https://github.com/rubyzip/rubyzip:

 Rubyzip interface changed!!! _No need to do *_require "zip/zip"*

I solved my problem in the way I told you, so do as you prefer: e.g. you
could put a condition based on version of rubyzip... or do nothing... for
me it's the same, now

Greetings
Riccardo

**Comment by two-pack** [comment]
This patch cannot run in Redmine 2.3.4 because selenium-webdriver needs rubyzip < 1.0.0.

**Comment by two-pack** [comment]
This patch don't run in my environment(Redmine 2.4.2).
And zip function is disable with original features branch.

R-i-c-k-y, Please tell me your environment details.
And didn't you patch init.rb and Gemfile?

**Comment by two-pack** [comment]
I think a file which should be changed is Gemfile:
I tried this in Redmine 2.4.2, result is good.

```
diff --git a/Gemfile b/Gemfile
index 51ac128..4723bae 100644
--- a/Gemfile
+++ b/Gemfile
@@ -4,5 +4,6 @@ gem "spreadsheet"

 group :export_attachments do
   gem "rubyzip"
+  gem 'zip-zip'
 end
```

But in Redmine 2.3.4, selenium-webdriver gem in test group requires rubyzip < 1.0.0. Therefore it conflicts zip-zip.

**Comment by two-pack** [comment]
Above commit resolves this problem, but I'm going to find better way.

**Comment by two-pack** [comment]
I change default specified gem because current maintenance version for Redmine are 2.4.x and 2.5.x.

And I specified version for rubyzip and zip-zip because rubyzip 1.10 or later and zip-zip 0.2 has compatible problem.
I pull-request following to zip-zip github.
https://github.com/orien/zip-zip/pull/5

**Comment by two-pack** [comment]
RubyZip v1.1.3 has been released with the fix. See
https://github.com/orien/zip-zip/pull/6
https://github.com/rubyzip/rubyzip/pull/152

I fixed rubyzip verison in Gemfile for above fix.

**Pull request closed without merging**
