### PR TITLE
Czech localisation + plugin settings view updated

### PR DESCRIPTION
**Pull request by picman**
- Czech localization updated
- Plugin settings view updated:
1. I've reformatted the floating text controls in the plugin settings that were overlapping
2. I've append an info text with default values

### CODE REVIEW

**Comment by two-pack** [comment]
Does the translation have a relation of changing view?
If not, please devide the issue to the translation and the view change.

Thanks you your help.

**Comment by picman** [comment]
The localization has no relation to the view reformatting. That's the reason why I have done two commits. What do you mean with "devide the issue"? I'm not allowed to create another pull request while there exists another not yet merged. The only reason why I have created the issue is that it's created automatically when you do a pull request.

**Comment by two-pack** [comment]
> The localization has no relation to the view reformatting. That's the reason why I have done two commits.

I see.

>  What do you mean with "devide the issue"?

I think a Issue (also called Ticket, Pull-request and so) has a mean (or reason) which exist. And I also think commits SHOULD relate a mean of tikect.
Now, The reason of your translation is different from the reason of your view change, so I think issue should be divided 'Czech translation' and 'Plugin settings view has invalid with overwrapping.'.

NOTE: The way of thinking is Ticket Driven Development (TiDD). See http://blogs.atlassian.com/2013/03/what-is-ticket-driven-development-and-why-is-it-attracting-attention-in-japan/

> I'm not allowed to create another pull request while there exists another not yet merged. The only reason why I have created the issue is that it's created automatically when you do a pull request. 

Ok. Please re-request them which is 2 issues after I'll close this issue without merge this.
I think TiDD is good practice, but If you don't now, comment it.

I really thank you contributing this plugin :)

**Comment by picman** [comment]
Tatsuya,
The only way how to contribute to the project is to create a pull
request. When I create a pull request, an issue is automatically
created. The relation between pull requests and commits is not 1:1 but
1:N. In other words you can't create a new pull request for a next
commit.

Can you explain me how to create two issues and to upload my code
changes when I've already pushed two commits into my fork of the
project. I'm afraid that I don't know how to do that. TiDD is clear but
how to work according the rules in GitHub?

## Best regards,

Karel Picman
Senior IT Consultant
Kontron ECT Pilsen
Tel. +420 378 775 485
Mob. +420 608 136 974
http://www.kontron.com

**Comment by two-pack** [comment]
You create 2 topic branches on your repository.
First branch is commited the translation. Another branch is commited the view change.
Then, You can probably create 2 pull-requests from branches.

**Comment by picman** [comment]
I'm sorry but I'm not wiling to create an extra branch for each commit.
It's counterproductive and also against Git philosophy. Please merge my
changes. I'm afraid that we're wasting of our time.

Your approach requires to do a pull request after each commit and before
a next commit a developer must wait for you to merge the pull request
because Github doesn't support multiple pull requests done by a single
user.

If you  insist on an issue for each commit, I can create two issues and
put a link to the corresponding commit into the description field.

## 

Karel Picman
Senior IT Consultant
Kontron ECT Pilsen
Tel. +420 378 775 485
Mob. +420 608 136 974
http://www.kontron.com

**Comment by two-pack** [comment]
Ok, time is money :)
I'll create devided issues with relation of this.
And I'll check and commit your cotribution.

**Comment by picman** [comment]
Thank you :-)

**Comment by two-pack** [comment]
I merged this request on #31 and #32 .
Thanks your contribution :)

**Comment by cforce** [comment]
sorry, but this is buggy see #33

**Pull request closed without merging**
