### PR TITLE
Assorted fixes: Relative URL Root, Rails3 before_filter, Date format in Journals export

### PR DESCRIPTION
**Pull request by vjt**
Hello,

I recently added this plugin to a Redmine 2.4 installation, and it works well. Below some assorted fixes:

* Honor RAILS_RELATIVE_URL_ROOT (c9a6aef)
* Use before_filter on R3/R4 and before_action on newer rails (03af38b)
* Correct date format in journals export (b65e06b)

And one addition:

* Add issue ID in journals export (7344a84)

I hope that it is OK for you to have a single pull request rather than four :-). I couldn't run tests on my 2.4 instance, but I'll fix any breakage highlighted by travis.

Cheers,

### CODE REVIEW

**Comment by vjt** [comment]
yay no build error 🎉

**Comment by two-pack** [comment]
Thank you for requesting :)
I'll check your work.

**Comment by two-pack** [comment]
I checked your request.
I think this request should be split by bug-fix or addition.
Could you split them and re-request?

**Comment by vjt** [comment]
OK

**Comment by two-pack** [comment]
> Add issue ID in journals export (7344a84)

What purpose is your change?
**Issues journals as separate files** exports by issues, so issue id isn't present.

**Comment by vjt** [comment]
>>Add issue ID in journals export (7344a84)

>What purpose is your change?

The purpose is to perform data analytics using software that can not get the issue id from the export filename.

**Comment by two-pack** [comment]
> The purpose is to perform data analytics using software that can not get the issue id from the export filename.

I see.
I think journal files should NOT be separated in this case, and also add option to switch it.
Present users may use analytics with now format, so I'm cautious to merge it.

**Comment by vjt** [comment]
Sensible. I can happily add the option.

**Pull request closed without merging**
